### ISSUE TITLE
Detected Artifacts on Xina

### ISSUE THREAD

**Issue by ibrahimqatar** [jjolano/HookKit#2]
Is this normal to have these with all options being on? (Cydia substrate is selected).

![image](https://user-images.githubusercontent.com/18020735/211299529-40ef115a-aa0b-4e43-adf8-57e1c17b5d3a.png)

![image](https://user-images.githubusercontent.com/18020735/211297848-edce4690-4b9e-4fed-ae19-06913b3a57bc.png)

**Comment by jjolano** [comment]
Bastille is my own detection framework. Have to play both sides and break the system to improve detection methods.

Also, not HookKit related at all 😆

**Comment by ibrahimqatar** [comment]
Yea I know I closed it here and opened it in your app's repo hahaha.

I thought maybe this is why teams and outlook gets detected on Xina and not Taurine
