### ISSUE TITLE
Does not work after updating the latest version

### ISSUE THREAD

**Issue by doimty** [jjolano/HookKit#3]
![image](https://user-images.githubusercontent.com/78968666/228095553-eb01750f-d630-4b92-86c7-3c82e4319f6a.png)
![image](https://user-images.githubusercontent.com/78968666/228095584-d3ab5bff-474d-4a5e-ba6a-5568454f4a64.png)

**Comment by doimty** [comment]
iOS13.6

**Comment by doimty** [comment]
iPhone 11

**Comment by jjolano** [comment]
The latest versions drop support for iOS less than 14 on arm64e devices. I will pull these builds and instead do it for rootless only.

Downgrade to the previous version, or reinstall after the next repo update.
